title: মনিরার জন্য গোপন বার্তা
description: A collection of romantic poems and messages for Monira
baseurl: "/monira-love-letters"
url: "https://fahimshahir.github.io"
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default" 